name: lang_test
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.3
  build_runner: ^2.1.7

dev_dependencies:
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
  assets:
    - assets/lang.yaml
    - assets/lang.json

scripts:
  pre-build:
    - bash ./run_script.sh
