name: lang_test
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/lang.json
build:
  pre-build:
    - python convert_yaml_to_json.py